/*
 * InfrawrenchSDK v1.24.0 | MIT | Copyright (c) 2026 Infrawrench LLC
 * https://github.com/Infrawrench/Infrawrench
 *
 * Generated from the Infrawrench API OpenAPI 3.1 spec (API version 1.24.0).
 *
 * DO NOT EDIT. Regenerate with:
 *   pnpm --filter @infrawrench/web generate:sdk
 *
 * Internal routes are absent by construction: the generator consumes the same
 * published spec that /openapi.json serves, which drops every operation
 * marked x-internal.
 */
import Foundation

public struct IacStatesCreateResult: Codable, Hashable, Sendable {
    public var state: IacState

    public init(
        state: IacState
    ) {
        self.state = state
    }
}

/// `client.iac`
public final class IacNamespace: Sendable {
    /// Shared request plumbing.
    let transport: ApiTransport
    /// `client.iac.states`
    public let states: IacStatesNamespace

    init(transport: ApiTransport) {
        self.transport = transport
        self.states = IacStatesNamespace(transport: transport)
    }

    /// Generate Terraform import blocks for unmanaged resources
    ///
    /// Terraform 1.5+ `import` blocks plus the matching resource stanzas,
    /// generated by the same plugin export mappers and HCL serializer that back
    /// "Export to Terraform…". Resources no plugin can express are returned in
    /// `unsupported` with a reason, never dropped.
    ///
    /// POST /api/org/{orgId}/iac/import-plan
    ///
    /// Raises on 400: Bad request
    ///
    /// Raises on 404: Not found
    ///
    /// - Parameter orgId: Organization id. Defaults to the `orgId` the client was
    /// created with.
    public func importPlan(
        orgId: String? = nil,
        body: IacImportPlanRequest? = nil,
        options: RequestOptions? = nil
    ) async throws -> IacImportPlanResponse {
        return try await transport.send(
            RequestSpec(
                method: "POST",
                path: "/api/org/{orgId}/iac/import-plan",
                pathParameters: ["orgId": orgId?.parameterValue],
                body: body.map { AnyEncodable($0) }
            ),
            options: options
        )
    }

    /// Classify inventory against a state document
    ///
    /// Every synced resource classified as managed, drifted or unmanaged against
    /// one uploaded state, plus state entries with no inventory match. Unmanaged
    /// resources carry the ownership and first-seen join that answers "who made
    /// this by hand, and when".
    ///
    /// GET /api/org/{orgId}/iac/reconciliation
    ///
    /// Raises on 400: Bad request
    ///
    /// Raises on 404: Not found
    ///
    /// - Parameter orgId: Organization id. Defaults to the `orgId` the client was
    /// created with.
    public func reconciliation(
        orgId: String? = nil,
        stateId: String,
        options: RequestOptions? = nil
    ) async throws -> IacReconciliationResponse {
        return try await transport.send(
            RequestSpec(
                method: "GET",
                path: "/api/org/{orgId}/iac/reconciliation",
                pathParameters: ["orgId": orgId?.parameterValue],
                query: [QueryParameter("stateId", stateId)]
            ),
            options: options
        )
    }

    /// IaC status for one resource
    ///
    /// The managed/unmanaged badge for a resource detail page, computed against
    /// the newest state document. `status` is null when the organization has
    /// uploaded none — absence of a state is not evidence of ClickOps. A query
    /// parameter rather than a path segment because composite resource ids
    /// contain slashes.
    ///
    /// GET /api/org/{orgId}/iac/resource
    ///
    /// Raises on 400: Bad request
    ///
    /// - Parameter orgId: Organization id. Defaults to the `orgId` the client was
    /// created with.
    public func resource(
        orgId: String? = nil,
        resourceId: String,
        options: RequestOptions? = nil
    ) async throws -> IacResourceStatusResponse {
        return try await transport.send(
            RequestSpec(
                method: "GET",
                path: "/api/org/{orgId}/iac/resource",
                pathParameters: ["orgId": orgId?.parameterValue],
                query: [QueryParameter("resourceId", resourceId)]
            ),
            options: options
        )
    }
}

/// `client.iac.states`
public final class IacStatesNamespace: Sendable {
    /// Shared request plumbing.
    let transport: ApiTransport

    init(transport: ApiTransport) {
        self.transport = transport
    }

    /// Upload a Terraform state document
    ///
    /// Parses a `.tfstate` (format version 4) or `terraform show -json` output
    /// (format_version 1.x) and records the resource instances it contains.
    /// Attributes the state marks sensitive are dropped before anything is
    /// written. The format version is checked, not assumed: an unsupported
    /// version is a 400 rather than a partial read.
    ///
    /// POST /api/org/{orgId}/iac/states
    ///
    /// Raises on 400: Bad request
    ///
    /// Raises on 404: Not found
    ///
    /// - Parameter orgId: Organization id. Defaults to the `orgId` the client was
    /// created with.
    public func create(
        orgId: String? = nil,
        body: IacStateUploadRequest? = nil,
        options: RequestOptions? = nil
    ) async throws -> IacStatesCreateResult {
        return try await transport.send(
            RequestSpec(
                method: "POST",
                path: "/api/org/{orgId}/iac/states",
                pathParameters: ["orgId": orgId?.parameterValue],
                body: body.map { AnyEncodable($0) }
            ),
            options: options
        )
    }

    /// Delete an uploaded state document
    ///
    /// DELETE /api/org/{orgId}/iac/states/{stateId}
    ///
    /// Raises on 404: Not found
    ///
    /// - Parameter orgId: Organization id. Defaults to the `orgId` the client was
    /// created with.
    public func delete(
        orgId: String? = nil,
        stateId: String,
        options: RequestOptions? = nil
    ) async throws {
        try await transport.sendVoid(
            RequestSpec(
                method: "DELETE",
                path: "/api/org/{orgId}/iac/states/{stateId}",
                pathParameters: ["orgId": orgId?.parameterValue, "stateId": stateId.parameterValue]
            ),
            options: options
        )
    }

    /// List uploaded Terraform state documents
    ///
    /// Every state document the organization has uploaded, newest first. The
    /// documents themselves are never stored — only the parsed, redacted
    /// projection.
    ///
    /// GET /api/org/{orgId}/iac/states
    ///
    /// - Parameter orgId: Organization id. Defaults to the `orgId` the client was
    /// created with.
    public func get(
        orgId: String? = nil,
        options: RequestOptions? = nil
    ) async throws -> IacStateListResponse {
        return try await transport.send(
            RequestSpec(
                method: "GET",
                path: "/api/org/{orgId}/iac/states",
                pathParameters: ["orgId": orgId?.parameterValue]
            ),
            options: options
        )
    }
}
